# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {

    "/" = { 
        #device = "/dev/disk/by-uuid/12ea94ee-4e11-4739-b5f0-5bb8ced9ea43";
	device = "/dev/disk/by-label/main";
        fsType = "btrfs";
        options = [ "subvol=@" "compress=zstd" "noatime" ];
      };

    "/home" = { 
        #device = "/dev/disk/by-uuid/12ea94ee-4e11-4739-b5f0-5bb8ced9ea43";
	device = "/dev/disk/by-label/main";
        fsType = "btrfs";
        options = [ "subvol=@home" "compress=zstd" "noatime" ];
      };

    "/nix" = { 
        #device = "/dev/disk/by-uuid/12ea94ee-4e11-4739-b5f0-5bb8ced9ea43";
	device = "/dev/disk/by-label/main";
        fsType = "btrfs";
        options = [ "subvol=@nix" "compress=zstd" "noatime" ];
      };

    "/boot" = { 
        #device = "/dev/disk/by-uuid/12CE-A600";
	device = "/dev/disk/by-label/BOOT";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

  };

  swapDevices = [ 
    { 
      #device = "/dev/disk/by-uuid/1972945f-6bc0-498d-b029-b4e23462b2f5"; 
      device = "/dev/disk/by-label/swap";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
